# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Twitter', '0003_tweetuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Twitter.TweetUser'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='liked_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_tweer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='tweet_resp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Twitter.Tweet'),
        ),
    ]
